name: .NET MAUI Desktop

on:
  push:
    branches: ["master"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["master"]

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: OwlReadingRoom.sln
      Maui_Project_Path: OwlReadingRoom.csproj
      Package_Path: AppPackages

      # Define your environment variables here
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_REDIRECT_URI: ${{ secrets.AUTH0_REDIRECT_URI }}
      AUTH0_POST_LOGOUT_REDIRECT_URI: ${{ secrets.AUTH0_POST_LOGOUT_REDIRECT_URI }}

      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_SENDER_NAME: ${{ secrets.SMTP_SENDER_NAME }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
      SMTP_RECEIVER_NAME: ${{ secrets.SMTP_RECEIVER_NAME }}
      SMTP_USE_SSL: ${{ secrets.SMTP_USE_SSL }}

      FEATURE_ROOM_ACTIONS_DELETE: ${{ secrets.FEATURE_ROOM_ACTIONS_DELETE }}
      FEATURE_ROOM_ACTIONS_EDIT: ${{ secrets.FEATURE_ROOM_ACTIONS_EDIT }}
      FEATURE_ROOM_ACTIONS_VIEW: ${{ secrets.FEATURE_ROOM_ACTIONS_VIEW }}

      FEATURE_PACKAGE_ACTIONS_DELETE: ${{ secrets.FEATURE_PACKAGE_ACTIONS_DELETE }}
      FEATURE_PACKAGE_ACTIONS_EDIT: ${{ secrets.FEATURE_PACKAGE_ACTIONS_EDIT }}
      FEATURE_PACKAGE_ACTIONS_VIEW: ${{ secrets.FEATURE_PACKAGE_ACTIONS_VIEW }}

      COMPANY_NAME: ${{ secrets.COMPANY_NAME }}
      COMPANY_ADDRESS: ${{ secrets.COMPANY_ADDRESS }}
      COMPANY_CITY: ${{ secrets.COMPANY_CITY }}
      COMPANY_MOBILE_NO: ${{ secrets.COMPANY_MOBILE_NO }}
      COMPANY_ALTERNATE_MOBILE_NO: ${{ secrets.COMPANY_ALTERNATE_MOBILE_NO }}
      COMPANY_EMAIL_ID: ${{ secrets.COMPANY_EMAIL_ID }}
      COMPANY_ALTERNATE_EMAIL_ID: ${{ secrets.COMPANY_ALTERNATE_EMAIL_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version
        id: set_version
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}".TrimStart('v')
          } else {
            $version = "1.0.0-preview.${{ github.run_number }}"
          }
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

          # Also set a clean version number without 'v' prefix for file names
          $cleanVersion = $version -replace '[^0-9.]', ''
          echo "CLEAN_VERSION=$cleanVersion" >> $env:GITHUB_ENV

          # Set the WindowsPackageVersion to the clean version
          echo "WINDOWS_PACKAGE_VERSION=$cleanVersion" >> $env:GITHUB_ENV

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install .NET MAUI Windows workload
        run: dotnet workload install maui-windows

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: dotnet restore $env:Solution_Name

      - name: Replace Environment Variables in appsettings.json
        run: |
          .\.github\scripts\replace_env_vars.ps1

      - name: Decode and Import Certificate
        if: github.actor != 'dependabot[bot]'
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
          $certificatePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath GitHubActionsWorkflow.pfx
          [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
          $password = ConvertTo-SecureString "${{ secrets.Pfx_Key }}" -AsPlainText -Force
          Import-PfxCertificate -FilePath $certificatePath -CertStoreLocation Cert:\CurrentUser\My -Password $password
          $cert = Get-PfxCertificate -FilePath $certificatePath -Password $password
          echo "CERTIFICATE_THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV

      - name: Build and package .NET MAUI project
        run: |
          $packageDir = Join-Path $env:GITHUB_WORKSPACE $env:Package_Path
          New-Item -ItemType Directory -Force -Path $packageDir

          # Conditionally include PFX-related parameters
          $certParams = @()
          if ("${{ github.actor }}" -ne "dependabot[bot]") {
            $certParams = @(
              "/p:PackageCertificateThumbprint=$env:CERTIFICATE_THUMBPRINT",
              "/p:AppxPackageSigningEnabled=true",
              "/p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx"
            )
          }

          msbuild $env:Maui_Project_Path `
            /p:Configuration=$env:Configuration `
            /p:Platform="x86" `
            /p:WindowsPackageType=MSIX `
            /p:WindowsAppSDKSelfContained=true `
            /t:Restore,Build,Publish `
            /p:TargetFramework=net8.0-windows10.0.19041.0 `
            /p:AppxPackageDir="$packageDir\" `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x86" `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:EnableMsixTooling=true `
            /p:GenerateAppxPackageOnBuild=true `
            /p:AppxPackageDir="$packageDir\" `
            /p:WindowsPackageVersion=$env:WINDOWS_PACKAGE_VERSION `
            @certParams
        env:
          Configuration: ${{ matrix.configuration }}

      # Create a ZIP file of the AppPackages directory (only for tag pushes)
      - name: Create Release ZIP
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          Compress-Archive -Path "$env:Package_Path\*" -DestinationPath "OwlReadingRoom-$env:PACKAGE_VERSION.zip" -Force

      # Create release and upload ZIP (only for tag pushes)
      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          # Create the release
          gh release create "${{ github.ref_name }}" `
            --title "Release ${{ github.ref_name }}" `
            --draft

          # Upload the ZIP file to the release
          gh release upload "${{ github.ref_name }}" "OwlReadingRoom-$env:PACKAGE_VERSION.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts for workflow run (only for tag pushes)
      - name: Upload build artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: OwlReadingRoom-${{ env.PACKAGE_VERSION }}
          path: AppPackages

      # Remove Certificate and Files (only for non-Dependabot runs)
      - name: Remove Certificate and Files
        if: github.actor != 'dependabot[bot]'
        run: |
          Remove-Item -path GitHubActionsWorkflow.pfx
          Get-ChildItem Cert:\CurrentUser\My\$env:CERTIFICATE_THUMBPRINT | Remove-Item
